// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPAk4rVfYhPrJ0ekIN53M9hEe3YkrwTUU',
    appId: '1:200874199843:web:b91f461dfa85c7b56f5a96',
    messagingSenderId: '200874199843',
    projectId: 'youth-care-b8068',
    authDomain: 'youth-care-b8068.firebaseapp.com',
    storageBucket: 'youth-care-b8068.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkUft4_Y92PDND7i55jRM9OixA-8rWg-g',
    appId: '1:200874199843:android:333534ead61dac356f5a96',
    messagingSenderId: '200874199843',
    projectId: 'youth-care-b8068',
    storageBucket: 'youth-care-b8068.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmEoUuzd08r4RvuQBe1H5g3gaZFlIXLd0',
    appId: '1:200874199843:ios:08cd60fdc87d48e76f5a96',
    messagingSenderId: '200874199843',
    projectId: 'youth-care-b8068',
    storageBucket: 'youth-care-b8068.appspot.com',
    iosClientId: '200874199843-95j95333jn2onecmq0o0tc9clc8gtrn0.apps.googleusercontent.com',
    iosBundleId: 'com.example.youthCare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBmEoUuzd08r4RvuQBe1H5g3gaZFlIXLd0',
    appId: '1:200874199843:ios:08cd60fdc87d48e76f5a96',
    messagingSenderId: '200874199843',
    projectId: 'youth-care-b8068',
    storageBucket: 'youth-care-b8068.appspot.com',
    iosClientId: '200874199843-95j95333jn2onecmq0o0tc9clc8gtrn0.apps.googleusercontent.com',
    iosBundleId: 'com.example.youthCare',
  );
}
